### PR TITLE
Support for firebase analytics (Without Null Safety)

### PR DESCRIPTION
**Pull request by danielgomezrico**
This fix https://github.com/claimsforce-gmbh/flutter-segment/issues/65 but for non-null safety version.

### CODE REVIEW

**Comment by divingyan** [comment]
Does this currently work? I am attempting to use this and I think there's issues with where the google-services.json file is located, as I'm getting this error:

```
E/AndroidRuntime(22505): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f150001
```

**Comment by danielgomezrico** [comment]
I wasnt able to make it work because of a dependency resolution issue between flutter firebase and segment firebase, so Im not sure

**Comment by danielgomezrico** [comment]
This is not been worked in the moment, @divingyan feel free to send a new PR with the feature :)

**Comment by ducNN93** [comment]
hey guys, is this feature available ?

**Comment by danielgomezrico** [comment]
@ducNN93 you can use it if you ping it directly to the branch and this repository in the pubspec, like this:

```yaml
    flutter-segment:
       git:
         url: https://github.com/la-haus/flutter-segment.git
         ref: feature/enable-firebase-without-null-safety
```

But at the time we tried there were an issue building the code, if you want it PRs are welcome! 🤓

**Pull request closed without merging**
