### PR TITLE
[Android] Update Segment and Amplitude integration

### LINKED ISSUE #30: Google Play policies violation in flutter_segment 3.7.0
After pushing another update for the app I am currently working on I saw the following warning in Play Developer Console:

> The following SDK versions are non compliant with Google Play policies:
> 
> com.segment.analytics.android:analytics:4.10.0
> The SDK collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.
> 
> Starting from August 9, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy will be blocked from release. You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.
> 
> According to the information provided by your SDK provider, you may consider upgrading to4.10.1. Please consult the SDK provider for further information.
> 
> Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981%20#resubmit).
> 
> If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk).

Checked the Segment Android SDK and saw that in 4.10.1 the issue was resolved: https://github.com/segmentio/analytics-android/blob/master/CHANGELOG.md#version-4101-jan-11-2022

Considering that 9th of August is pretty soon already and release cycle of `flutter_segment` isn't that short, it is worth to update the Segment Android SDK and release an update for the `flutter_segment`.

Issues occurs with `flutter_segment 3.7.0`

P.S. I will open a PR with needed changes.

### PR DESCRIPTION
**Pull request by vbuberen**
Updates for Android Segment dependencies to address Google Play policies violation and keep the project up to date.

Both updated dependencies had no breaking changes inside, so nothing breaking is expected from this update:
https://github.com/segmentio/analytics-android/blob/master/CHANGELOG.md
https://github.com/segment-integrations/analytics-android-integration-amplitude/blob/master/CHANGELOG.md

Suggest to merge this PR after #29 , because to test this branch a person would need to do adjustments already done in mentioned PR, like change in AndroidManifest of `android:name` to not use embedding V1.

Closes #30

### CODE REVIEW

**Review by danielgomezrico — APPROVED** [review]
Nice, thanks for the PR

**Comment by danielgomezrico** [comment]
@vbuberen do you know why it fails? it may be related to https://github.com/la-haus/flutter-segment/pull/29

**Comment by vbuberen** [comment]
> @vbuberen do you know why it fails? it may be related to #29

Yes, it was related. This is why I was asking when #29 will be merged. Updated the branch with new changes and everything is fine now on CI.

**Review by hokstuff — APPROVED** [review]
Nice, I was just about to make a PR myself to address #30 🚀 

Do we want to include a Changelog entry?
```
* Android: upgrade Segment SDK to 4.10.4
```

**Comment by tspoke** [comment]
Hi, do you have an ETA for this PR and a new version ? 
This is really blocking us for deploying our new app on Google Play.
Thank you!

**Comment by vbuberen** [comment]
> Do we want to include a Changelog entry?

There is no info from core maintainers on if and how they want contributors from the outside to mention new changes or bump version, so I think it is up to core maintainers to do so when they decide to do a new release.

> This is really blocking us for deploying our new app on Google Play.

Out of curiosity how it can be blocking if the new policy will be enforced on 9th of August?

**Comment by tspoke** [comment]
From codemagic (our CI), we are not allowed to publish due to this : 

```
Publishing failed :|
Google Play failed to upload artefacts. Your artifact (version code 2102) contains an SDK (com.segment.analytics.android:analytics) with version 4.10.0 that collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy: https://support.google.com/googleplay/android-developer/answer/10144311. To be allowed to publish, you may consider upgrading to 4.10.1 which the SDK provider has recommended for use instead. Please consult the SDK provider for further information.Read through the User data policy: https://support.google.com/googleplay/android-developer/answer/10144311 policy for more details, and how to submit an updated app for review here: https://support.google.com/googleplay/android-developer/answer/2477981#resubmit. If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team: https://play.google.com/console/appealsForm?aid=XXXXXXX&ts=SR. For more information see https://support.google.com/googleplay/android-developer/answer/10358880.: {
    "error": {
        "code": 403,
        "message": "Your artifact (version code 2102) contains an SDK (com.segment.analytics.android:analytics) with version 4.10.0 that collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy: https://support.google.com/googleplay/android-developer/answer/10144311. To be allowed to publish, you may consider upgrading to 4.10.1 which the SDK provider has recommended for use instead. Please consult the SDK provider for further information.Read through the User data policy: https://support.google.com/googleplay/android-developer/answer/10144311 policy for more details, and how to submit an updated app for review here: https://support.google.com/googleplay/android-developer/answer/2477981#resubmit. If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team: https://play.google.com/console/appealsForm?aid=XXXXXXX&ts=SR. For more information see https://support.google.com/googleplay/android-developer/answer/10358880.",
        "status": "PERMISSION_DENIED"
    }
}

**Comment by vbuberen** [comment]
> From codemagic (our CI), we are not allowed to publish due to this :

Interesting. It happened in last few days, right? 
Because on my project Codemagic uploaded build last Monday and still could do it, so I saw the message about this SDK only in the Developer Console.

**Comment by tspoke** [comment]
This is the first release with segment that we have built and try to deploy. Last week we released a version without segment with success so I can't tell if it's recent or not.

**Comment by saigkl** [comment]
@danielgomezrico - Any ETA on when this will get merged?

**Comment by vbuberen** [comment]
> Last week we released a version without segment with success so I can't tell if it's recent or not.

Seems like Google treats apps, which already had Segment and which added it recently in a different way. 
Just tried to trigger a new build on Codemagic for my project, which uses Segment for quite some time already and publishing worked fine, so I only see the warning in the Developer Console as it was before.

Screenshot 2022-06-13 at 12 42 18

**Comment by zenled** [comment]
Hey, 
Has anyone tried to upload a build with the updated versions of Segment-Android and Amplitude-Android, did it fix the warning? 

I noticed that in [this issue](https://github.com/segmentio/analytics-android/issues/801#issuecomment-1152491861) and [this issue](https://github.com/segmentio/analytics-android/issues/802#issuecomment-1154072729) they mention:

> if you're using any device mode integration, you probably will see this warning even if you updated to 4.10.4. that's because the integration sdks internally uses an old version of analytics-android. a fix to that is underway.

And since `flutter-segment` depends on Amplitude-Android which [depends on an older version of Segment-Android](https://github.com/segment-integrations/analytics-android-integration-amplitude/blob/ee8e61f988f81843f5f4ae558950eb1d7453a138/build.gradle#L52), I assume we will still see the warning. ([relevant issue](https://github.com/segment-integrations/analytics-android-integration-amplitude/issues/60))

**Pull request merged**
